list_of_packages <- c("knitr",
                      "tidyverse",
                      "caret",
                      "e1071",
                      "ggplot2",
                      "forcats",
                      "dplyr",
                      "lmtest",
                      "car",
                      "pROC",
                      "arules",
                      "arulesViz",
                      # "ElemStatLearn",
                      "ISLR",
                      "glmnet",
                      "gam",
                      "class",
                      "nnet",
                      "rpart",
                      "party",
                      "partykit",
                      "randomForest",
                      "ROCR",
                      "boot",
                      "bayesboot",
                      "mboost",
                      "ada",
                      "MDPtoolbox",
                      "tm",
                      "SnowballC",
                      "ggmap",
                      "plyr",
                      "ggthemes",
                      "reshape",
                      "nycflights13",
                      "kohonen"
)

new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if (length(new_packages) > 0) install.packages(new_packages)
